name: vaanilai
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  geolocator: ^10.1.0
  http: ^1.1.0
  flutter_spinkit: ^5.2.0
  permission_handler: ^11.0.1
  google_api_availability: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: SpartanMB
      fonts:
        - asset: fonts/SpartanMB-Black.otf
          weight: 700
    - family: PlaypenSans
      fonts:
        - asset: fonts/PlaypenSans-VariableFont_wght.ttf
          weight: 700